name: Deploy Worker to Cloudflare

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'wrangler.jsonc'
      - 'package.json'
      - 'package-lock.json'
      - 'public/index.html'
      - 'scripts/install.sh'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Workers
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Publish Worker
        run: npx wrangler deploy
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
